name: Deploy dmX beta to GitHub Pages
on:
    push:
        branches: [beta]

permissions:
    contents: write
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: .
                  clean-exclude: pr-preview/
                  target-folder: beta/
