name: Deploy PR previews to GitHub Pages
concurrency: preview-${{ github.ref }}
on:
    pull_request_target:
        types:
            - opened
            - reopened
            - synchronize
            - closed

jobs:
    test:
        uses: key4hep/dmx/.github/workflows/test-previews.yml@main
        with:
            repository: ${{ github.event.pull_request.head.sha }}

    deploy-preview:
        needs: test
        environment: github-pages
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - name: Checkout PR
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Deploy to GH-Pages
              uses: rossjrw/pr-preview-action@v1
              id: preview_step
              if: contains(['opened', 'reopened', 'synchronize'], ${{ github.event.action }})
              with:
                  source-dir: .
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  deploy-repository: "key4hep/dmx"
                  token: ${{ secrets.PR_TOKEN }}
                  action: auto

            - name: Remove preview
              uses: rossjrw/pr-preview-action@v1
              if: github.event.action == 'closed' && !github.event.pull_request.merged
              with:
                  source-dir: .
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  deploy-repository: "key4hep/dmx"
                  token: ${{ secrets.PR_TOKEN }}
                  action: remove
