name: Test previews
on:
    workflow_call:
        inputs:
            repository:
                required: true
                type: string

jobs:
    test:
        environment: github-pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout PR
              uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.repository }}
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
